name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Debug - Show dist/index.html content
        run: |
          echo "=== Content of dist/index.html ==="
          head -n 50 dist/index.html
          echo "=== End of dist/index.html preview ==="

      - name: Verify Build
        run: |
          echo "Checking build output..."
          ls -la dist/
          if [ ! -f dist/index.html ]; then
            echo "Error: index.html not found in dist/"
            exit 1
          fi
          if [ ! -f dist/CNAME ]; then
            echo "Error: CNAME not found in dist/"
            exit 1
          fi
          if [ ! -f dist/.nojekyll ]; then
            echo "Error: .nojekyll not found in dist/"
            exit 1
          fi
          echo "Build verification successful!"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
